import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { checkRelease } from '../scripts/release-check.ts'

const dirs: string[] = []

afterEach(async () => {
  await Promise.all(dirs.splice(0).map((dir) => rm(dir, { recursive: true, force: true })))
})

/** A repository that is ready to tag as 1.2.3, with any file replaced. */
async function repo(overrides: Record<string, string> = {}): Promise<string> {
  const root = await mkdtemp(path.join(tmpdir(), 'eaa-kit-release-'))
  dirs.push(root)
  const files: Record<string, string> = {
    'package.json': JSON.stringify({ version: '1.2.3' }),
    'CHANGELOG.md': '# Changelog\n\n## 1.2.3 — 2026-10-01\n\n- Things.\n\n## 1.2.2 — 2026-09-01\n',
    'README.md': 'uses: likeBloodMoon/eaa-kit@v1.2.3\n',
    'docs/integrations.md': '- uses: likeBloodMoon/eaa-kit@v1.2.3\n',
    '.github/workflows/accessibility.yml': '#   uses: likeBloodMoon/eaa-kit@v1.2.3\n',
    'examples/report.json': JSON.stringify({ tool: { version: '1.2.3' } }),
    ...overrides,
  }
  for (const [name, body] of Object.entries(files)) {
    await mkdir(path.join(root, path.dirname(name)), { recursive: true })
    await writeFile(path.join(root, name), body)
  }
  return root
}

describe('release:check', () => {
  it('passes a repository that is ready, with and without the tag', async () => {
    const root = await repo()

    expect(await checkRelease({ root })).toEqual([])
    expect(await checkRelease({ root, tag: 'v1.2.3' })).toEqual([])
  })

  it('refuses a tag that does not match package.json, as v0.8.0 was', async () => {
    const problems = await checkRelease({ root: await repo(), tag: 'v1.2.4' })

    expect(problems).toEqual(['the tag is v1.2.4, but package.json says 1.2.3'])
  })

  it('refuses a changelog with no heading for the version', async () => {
    const root = await repo({ 'CHANGELOG.md': '# Changelog\n\n## 1.2.2 — 2026-09-01\n' })

    expect(await checkRelease({ root })).toEqual([
      'CHANGELOG.md has no "## 1.2.3 — <date>" heading',
    ])
  })

  it('refuses an undated heading and a leftover Unreleased section', async () => {
    const root = await repo({
      'CHANGELOG.md': '# Changelog\n\n## Unreleased\n\n## 1.2.3 — soon\n',
    })

    expect(await checkRelease({ root })).toEqual([
      'CHANGELOG.md still has an "Unreleased" section: date it, or move it under the version',
      'the CHANGELOG.md heading for 1.2.3 is not dated as YYYY-MM-DD',
    ])
  })

  it('names every file that pins the Action to another version', async () => {
    const root = await repo({
      'docs/integrations.md': '- uses: likeBloodMoon/eaa-kit@v1.2.2\n',
      '.github/workflows/accessibility.yml': '#   uses: likeBloodMoon/eaa-kit@v1.0.0\n',
    })

    expect(await checkRelease({ root })).toEqual([
      `${path.join('.github/workflows', 'accessibility.yml')} pins the Action to v1.0.0, not v1.2.3`,
      `${path.join('docs', 'integrations.md')} pins the Action to v1.2.2, not v1.2.3`,
    ])
  })

  it('refuses examples generated by another version', async () => {
    const root = await repo({
      'examples/report.json': JSON.stringify({ tool: { version: '1.2.2' } }),
    })

    expect(await checkRelease({ root })).toEqual([
      'examples/ was generated by 1.2.2: run pnpm examples and commit the result',
    ])
  })
})
