#!/usr/bin/env node
// What has to be true before a version is tagged. Run with `pnpm release:check`.
//
// v0.8.0 was tagged on a commit whose package.json still said 0.7.0. The
// release workflow caught that, but only after the tag was public, and a
// public tag is awkward to take back. Every item here has either gone wrong
// once or had to be remembered by hand at every release, so the list lives in
// code instead of in somebody's head, and CI runs it on the release PR,
// before anything is tagged.
//
// Pass the tag to compare against, as the release workflow does. Without one,
// the check is about the working tree alone.

import { readdir, readFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export interface ReleaseCheckOptions {
  root: string
  /** The tag being released, `v1.2.3`. Optional: a release PR has no tag yet. */
  tag?: string
}

/** Where the Action is pinned to an exact release. */
const PIN_FILES = ['README.md', 'docs', '.github/workflows']

const PIN = /likeBloodMoon\/eaa-kit@v(\d+\.\d+\.\d+(?:-[\w.]+)?)/g

/** Every problem that would make this commit the wrong one to tag, in words. */
export async function checkRelease(options: ReleaseCheckOptions): Promise<string[]> {
  const problems: string[] = []
  const read = (file: string): Promise<string> => readFile(path.join(options.root, file), 'utf8')

  const version = (JSON.parse(await read('package.json')) as { version: string }).version

  if (options.tag !== undefined && options.tag !== `v${version}`) {
    problems.push(`the tag is ${options.tag}, but package.json says ${version}`)
  }

  const changelog = await read('CHANGELOG.md')
  if (/^## Unreleased\b/m.test(changelog)) {
    problems.push(
      'CHANGELOG.md still has an "Unreleased" section: date it, or move it under the version',
    )
  }
  const heading = new RegExp(`^## ${version.replaceAll('.', '\\.')} — (\\S+)`, 'm').exec(changelog)
  if (heading === null) {
    problems.push(`CHANGELOG.md has no "## ${version} — <date>" heading`)
  } else if (!/^\d{4}-\d{2}-\d{2}$/.test(heading[1] ?? '')) {
    problems.push(`the CHANGELOG.md heading for ${version} is not dated as YYYY-MM-DD`)
  }

  for (const file of await markdownAndWorkflows(options.root)) {
    const text = await read(file)
    for (const match of text.matchAll(PIN)) {
      if (match[1] !== version) {
        problems.push(`${file} pins the Action to v${match[1]}, not v${version}`)
      }
    }
  }

  // The examples stamp the version, so a stale one means `pnpm examples` was
  // not re-run, and whatever else it would have changed has not been looked at.
  const report = JSON.parse(await read('examples/report.json')) as { tool: { version: string } }
  if (report.tool.version !== version) {
    problems.push(
      `examples/ was generated by ${report.tool.version}: run pnpm examples and commit the result`,
    )
  }

  return problems
}

async function markdownAndWorkflows(root: string): Promise<string[]> {
  const files: string[] = []
  for (const entry of PIN_FILES) {
    const full = path.join(root, entry)
    const listed = await readdir(full, { recursive: true }).catch(() => undefined)
    if (listed === undefined) {
      files.push(entry)
      continue
    }
    for (const name of listed) {
      if (/\.(md|ya?ml)$/.test(name)) files.push(path.join(entry, name))
    }
  }
  return files.sort()
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const tag = process.argv[2] ?? undefined
  const problems = await checkRelease(tag === undefined ? { root: '.' } : { root: '.', tag })
  if (problems.length === 0) {
    console.log('release:check ok')
  } else {
    for (const problem of problems) console.error(`✗ ${problem}`)
    process.exitCode = 1
  }
}
